NumPy basics and vectorized computation 
Exercises Name: Rovin Castelino
Registration Number: 240957001
PC 46
24/01/2025

1. Generate a 3x4 NumPy array with random integers between 1 and 50. 

In [1]:
import numpy as np
from random import *

In [2]:
L=[]
for i in range(12):
    L.append(randint(1,50))
arr=np.array(L)
arr=arr.reshape(3,4)
print(arr)

[[28 49 44 48]
 [ 7 28 47  9]
 [48 10  5 41]]


a. Calculate and print the Mean, Median, and Standard Deviation of the array 

In [3]:
mean=np.mean(arr)
median=np.median(arr)
sd=np.std(arr)
print("Mean is", mean)
print("Median is", median)
print("standard deviation is",sd)

Mean is 30.333333333333332
Median is 34.5
standard deviation is 17.360555546666383


b. Print the Sum of all elements and the sum of each row. 

In [4]:
i=0
total=0
for row in arr:
    print("sum of row",i,"is",np.sum(row))
    total+=np.sum(row)
    i+=1
print("Total is",total)

sum of row 0 is 169
sum of row 1 is 91
sum of row 2 is 104
Total is 364


c. Reshape the 3x4 array into a 2x6 array and print it. 

In [5]:
arr.reshape(2,6)

array([[28, 49, 44, 48,  7, 28],
       [47,  9, 48, 10,  5, 41]])

2. Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations

In [6]:
arr1=np.array([[2,2,2],[2,2,2],[2,2,2]])
arr2=np.array([[1,0,0],[0,1,0],[0,0,1]])
print("Array 1")
print(arr1)
print()
print("Array 2")
print(arr2)

Array 1
[[2 2 2]
 [2 2 2]
 [2 2 2]]

Array 2
[[1 0 0]
 [0 1 0]
 [0 0 1]]


a. Matrix addition 

In [7]:
print(arr1+arr2)

[[3 2 2]
 [2 3 2]
 [2 2 3]]


b. Matrix subtraction 

In [8]:
print(arr1-arr2)

[[1 2 2]
 [2 1 2]
 [2 2 1]]


c. Matrix multiplication (element-wise and dot product) 

In [9]:
print("Matrix Multiplication")
print(np.matmul(arr1,arr2))
print()
print("Dot Product")
print(np.dot(arr1,arr2))

Matrix Multiplication
[[2 2 2]
 [2 2 2]
 [2 2 2]]

Dot Product
[[2 2 2]
 [2 2 2]
 [2 2 2]]


d. Transpose of a matrix 

In [10]:
print("Normal Matrix")
print(arr)
print()
print("Transpose of Matrix")
print(arr.T)

Normal Matrix
[[28 49 44 48]
 [ 7 28 47  9]
 [48 10  5 41]]

Transpose of Matrix
[[28  7 48]
 [49 28 10]
 [44 47  5]
 [48  9 41]]


e. Determinant and inverse (if applicable) 

In [11]:
from numpy.linalg import inv, det
import math
X =np.array([[1,2,3],[5,6,7],[8,9,0]])
print("Determinant of Matrix is",det(X))
print()
if det(X)!=0:
    print("Inverse of the Matrix")
    print(inv(X))
else:
    print("Inverse is not possible")

Determinant of Matrix is 39.99999999999998

Inverse of the Matrix
[[-1.575  0.675 -0.1  ]
 [ 1.4   -0.6    0.2  ]
 [-0.075  0.175 -0.1  ]]
