NumPy
Name:Rovin Castelino
Registration Number: 240957001
PC 46
24/1/25

In [3]:
import numpy as np
my_arr = np.arange(10)
my_list = list(range(10))

In [4]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

890 ns ± 12.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
551 ns ± 6.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [11]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [15]:
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))
print(np.ones(10))
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1.19565654e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.10343781e-312 6.23034880e-038]]

 [[9.41821968e-067 8.30714921e-067]
  [1.73323735e+185 6.86568044e+169]
  [3.92334622e+179 1.77399833e+160]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(np.arange(15))
print(np.arange(3,15,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  6  9 12]


In [17]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [19]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

int32
[1. 2. 3. 4. 5.]
float64


In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [21]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
print(numeric_strings.astype(float))
numeric_strings = np.array(['1', '-9', '42'], dtype=np.string_)
print(numeric_strings.astype(int))
numeric_strings = np.array(["1", "-9", "42"], dtype=np.string_)
print(numeric_strings.astype(np.int32))

[ 1.25 -9.6  42.  ]
[ 1 -9 42]
[ 1 -9 42]


In [22]:
int_array = np.arange(10)
cal = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(cal.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
zeros_uint32 = np.zeros(8, dtype="u4")
print(zeros_uint32)

In [23]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
print(1 / arr)
print(arr ** 2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [26]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [32]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
a=arr[5:8] == 12 )
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[False False False]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [ ]:
arr_slice[1] = 12345 
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

In [ ]:
arr2d[0][2]

3

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

In [ ]:
x = arr3d[1]
x
x[0]

In [ ]:
arr
arr[1:6]

In [ ]:
arr2d

In [ ]:
arr2d
arr2d[:2] 

In [ ]:
arr2d[:2, 1:] #

In [ ]:
arr2d

In [ ]:
lower_dim_slice = arr2d[2, :2]
lower_dim_slice

In [ ]:
lower_dim_slice.shape

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0
arr2d

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [ ]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

array([7, 0])

In [ ]:
names != "Bob"

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

array([[4, 7],
       [0, 6],
       [0, 0],
       [1, 2]])

In [ ]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [ ]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [ ]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

**Swap axes**

In [ ]:
arr
arr.swapaxes(0, 1)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
x = np.random.standard_normal(8) 
y = np.random.standard_normal(8)
x
y

array([ 1.32098715,  0.77784584,  0.25036766,  0.85827789, -1.12113236,
        1.17969142, -1.07593303,  1.38893343])

In [ ]:
arr = np.random.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

array([ 1.,  0.,  1.,  0.,  2., -5., -9.])

In [ ]:
arr
np.add(arr, 1)

array([ 2.50260435,  1.26528323,  2.28635762,  1.17871431,  3.73618343,
       -4.6148079 , -8.87623834])

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:

np.where(arr > 0, 2, arr) 

In [ ]:
arr = np.random.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.mean(axis=1)
xArr.sum(axis=0)

In [ ]:
xArr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
xArr.cumsum()
xArr.cumprod()

In [ ]:
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.cumsum(0)

In [ ]:
xArr3d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
xArr3d
xArr3d.cumsum(axis=0)
xArr3d.cumprod(axis=1)

In [83]:

xArr = np.array([-5, 1, 2, -1, -4, -7, 3])
xArr
(xArr > 0).sum() 
(xArr <= 0).sum() 

4

In [76]:
bools = np.array([False, False, True, False])
bools.any()

True

In [63]:
arr = np.random.standard_normal(6)
arr
arr.sort()
arr

array([-0.85779058, -0.0928956 ,  0.12297438,  1.29199914,  1.61937963,
        2.48882931])

In [64]:
arr = np.random.standard_normal((5, 3))
arr

array([[ 0.43522325, -0.43933108,  2.24474216],
       [ 1.74481257, -0.11029615,  1.49901156],
       [ 1.54045699, -0.29167033, -1.276872  ],
       [-0.31921275, -0.42388507,  0.32128426],
       [-0.43196419, -0.66223105,  0.49909259]])

In [69]:
xArr = np.array([[5, 1, 2], [4, 7, 3]])
xArr.sort(axis=0)
xArr

array([[1, 2, 5],
       [3, 4, 7]])

In [72]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
np.sort(arr2)
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [59]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
names
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [60]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [61]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [52]:
arr = np.arange(10)
np.save("some_array", arr) 

In [53]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.savez("array_archive.npz", a=arr, b=arr)

In [55]:
arch = np.load("array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

In [26]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [27]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [38]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [51]:
from numpy.linalg import inv, det
X = np.random.standard_normal((5, 5))
mat = X.T @ X