NumPy
Name:Rovin Castelino
Registration Number: 240957001
PC 46
24/1/25

In [1]:
import numpy as np
my_arr = np.arange(10)
my_list = list(range(10))

In [2]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

517 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
280 ns ± 3.16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [4]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [5]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [9]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [10]:
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))
print(np.ones(10))
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.11879922e-310 5.29756219e-310]
  [0.00000000e+000 0.00000000e+000]
  [1.29441743e-312 2.25629673e+180]]

 [[9.43472494e+164 1.40075133e-076]
  [5.78253017e+174 1.91689075e-076]
  [5.20093532e-062 2.09130087e-076]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(np.arange(15))
print(np.arange(3,15,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  6  9 12]


In [12]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

int64
[1. 2. 3. 4. 5.]
float64


In [14]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [15]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
print(numeric_strings.astype(float))
numeric_strings = np.array(['1', '-9', '42'], dtype=np.bytes_)
print(numeric_strings.astype(int))
numeric_strings = np.array(["1", "-9", "42"], dtype=np.bytes_)
print(numeric_strings.astype(np.int32))

[ 1.25 -9.6  42.  ]
[ 1 -9 42]
[ 1 -9 42]


In [16]:
int_array = np.arange(10)
cal = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(cal.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [17]:
zeros_uint32 = np.zeros(8, dtype="u4")
print(zeros_uint32)

[0 0 0 0 0 0 0 0]


In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(1 / arr)
print(arr ** 2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [20]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [21]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
a=arr[5:8] == 12 
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[0 1 2 3 4 5 6 7 8 9]


In [22]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [23]:
arr_slice[1] = 12345 
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [24]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [26]:
arr2d[0][2]

np.int64(3)

In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[1, 0]

array([7, 8, 9])

In [31]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

In [32]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [33]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr2d
arr2d[:2] 

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2d[:2, 1:] #

array([[2, 3],
       [5, 6]])

In [36]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
lower_dim_slice = arr2d[2, :2]
lower_dim_slice

array([7, 8])

In [38]:
lower_dim_slice.shape

(2,)

In [39]:
arr2d[:2, 2]

array([3, 6])

In [40]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [41]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [42]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [43]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [44]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [45]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

array([7, 0])

In [46]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [47]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [48]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [49]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [50]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [51]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [52]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [53]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [54]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [56]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [57]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [61]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

**Swap axes**

In [62]:
arr
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [63]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [64]:
x = np.random.standard_normal(8) 
y = np.random.standard_normal(8)
x
y

array([-0.57393925,  0.72061517,  0.12266184,  0.95125409, -0.75998583,
       -1.24519724,  0.72974694, -0.72935378])

In [65]:
arr = np.random.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

array([ 6., -1.,  5.,  1.,  1.,  0., -4.])

In [66]:
arr
np.add(arr, 1)

array([ 7.45419194, -0.01172638,  6.41878081,  2.29634719,  2.37622347,
        1.30686645, -3.86027554])

In [67]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [68]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [69]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [70]:
arr = np.random.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [ 2, -2,  2,  2],
       [ 2,  2,  2, -2],
       [-2, -2, -2, -2]])

In [71]:

np.where(arr > 0, 2, arr) 

array([[-0.73076672,  2.        , -0.21432246,  2.        ],
       [ 2.        , -0.67199418,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.16031902],
       [-1.67753015, -0.99496697, -0.9952032 , -0.69813521]])

In [72]:
arr = np.random.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

np.float64(-1.2833617948949998)

In [73]:
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.mean(axis=1)
xArr.sum(axis=0)

array([5, 7, 9])

In [74]:
xArr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
xArr.cumsum()
xArr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
xArr = np.array([[1, 2, 3], [4, 5, 6]])
xArr.cumsum(0)

array([[1, 2, 3],
       [5, 7, 9]])

In [76]:
xArr3d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
xArr3d
xArr3d.cumsum(axis=0)
xArr3d.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [77]:

xArr = np.array([-5, 1, 2, -1, -4, -7, 3])
xArr
(xArr > 0).sum() 
(xArr <= 0).sum() 

np.int64(4)

In [78]:
bools = np.array([False, False, True, False])
bools.any()

np.True_

In [79]:
arr = np.random.standard_normal(6)
arr
arr.sort()
arr

array([-1.48094912, -1.11948919, -0.50248844, -0.06127621,  0.82663715,
        0.93626369])

In [80]:
arr = np.random.standard_normal((5, 3))
arr

array([[-0.18959801,  0.550876  ,  2.1450226 ],
       [-1.08298507,  0.99588113,  0.38741517],
       [ 0.82595883,  2.30945252, -0.78601922],
       [-1.89161704, -0.77589141,  0.87875852],
       [ 0.1220135 , -0.05332397, -0.43360494]])

In [81]:
xArr = np.array([[5, 1, 2], [4, 7, 3]])
xArr.sort(axis=0)
xArr

array([[4, 1, 2],
       [5, 7, 3]])

In [82]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
np.sort(arr2)
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [83]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
names
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [84]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

In [85]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

/tmp/ipykernel_24152/1293837718.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

In [86]:
arr = np.arange(10)
np.save("some_array", arr) 

In [87]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.savez("array_archive.npz", a=arr, b=arr)

In [89]:
arch = np.load("array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

In [91]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [92]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [93]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [94]:
from numpy.linalg import inv, det
X = np.random.standard_normal((5, 5))
mat = X.T @ X